version: 1.0.0
files:
  - url: XiaoELong Setup 1.0.0.exe
    sha512: 6/oyinhjFldz+8gim/z2Wdja3RtEivZ29Y7ZH4ko+Z04R0ULN46SeJnqq0Uj3pug8qC8pveK1tWAvjpBQl3c3Q==
    size: 80124059
path: XiaoELong Setup 1.0.0.exe
sha512: 6/oyinhjFldz+8gim/z2Wdja3RtEivZ29Y7ZH4ko+Z04R0ULN46SeJnqq0Uj3pug8qC8pveK1tWAvjpBQl3c3Q==
releaseDate: '2026-07-12T12:31:00.834Z'
